export const MOCK_ARTICLES = [
  {
    id: "1",
    title: "Making Tax Digital: The 2026 Guide for Small Businesses",
    slug: "making-tax-digital-2026-guide",
    excerpt: "Everything you need to know about the upcoming changes to HMRC's digital tax initiative and how to prepare your business.",
    category: { name: "Tax & Compliance", slug: "tax-compliance" },
    author_name: "Sarah Jenkins",
    published_at: "2026-03-15T10:00:00Z",
    read_time: 7,
    thumbnail_url: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=2000&auto=format&fit=crop",
    featured: true,
  },
  {
    id: "2",
    title: "Understanding the New Minimum Wage Increases",
    slug: "understanding-new-minimum-wage",
    excerpt: "A complete breakdown of the April wage adjustments and how to calculate the impact on your cash flow.",
    category: { name: "Payroll", slug: "payroll" },
    author_name: "David Chen",
    published_at: "2026-03-12T14:30:00Z",
    read_time: 5,
    thumbnail_url: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?q=80&w=2000&auto=format&fit=crop",
    featured: true,
  },
  {
    id: "3",
    title: "How to Chase Late Payments Without Losing the Client",
    slug: "chase-late-payments-gracefully",
    excerpt: "Credit control strategies that protect your cash flow and maintain strong relationships with your customers.",
    category: { name: "Invoicing & Payments", slug: "invoicing-payments" },
    author_name: "Editorial Team",
    published_at: "2026-03-10T09:15:00Z",
    read_time: 6,
    thumbnail_url: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "4",
    title: "The First 100 Days: Setting Up Your Bookkeeping System",
    slug: "setting-up-bookkeeping-system",
    excerpt: "A step-by-step checklist for configuring your chart of accounts, bank feeds, and initial bookkeeping settings.",
    category: { name: "Bookkeeping & Accounting", slug: "bookkeeping-accounting" },
    author_name: "Emma Wilson",
    published_at: "2026-03-08T11:00:00Z",
    read_time: 8,
    thumbnail_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "5",
    title: "Managing Statutory Sick Pay: A Quick Reference Guide",
    slug: "managing-statutory-sick-pay",
    excerpt: "Current rates, qualifying days, and the exact process for recording SSP in your payroll software.",
    category: { name: "HR & People", slug: "hr-people" },
    author_name: "James Thorne",
    published_at: "2026-03-05T13:45:00Z",
    read_time: 4,
    thumbnail_url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "6",
    title: "Sage vs Xero vs QuickBooks: Which Is Best for UK Small Businesses?",
    slug: "sage-vs-xero-vs-quickbooks",
    excerpt: "A detailed feature-by-feature comparison of the three leading cloud accounting platforms for UK SMEs.",
    category: { name: "Comparison", slug: "comparison" },
    author_name: "Sarah Jenkins",
    published_at: "2026-03-01T08:30:00Z",
    read_time: 12,
    thumbnail_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "7",
    title: "Best Cloud Accounting Software for Freelancers in 2026",
    slug: "best-cloud-accounting-freelancers-2026",
    excerpt: "We tested 8 popular platforms to find the best cloud accounting tools built for sole traders and freelancers.",
    category: { name: "Cloud Software", slug: "cloud-software" },
    author_name: "Emma Wilson",
    published_at: "2026-02-28T10:00:00Z",
    read_time: 10,
    thumbnail_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "8",
    title: "VAT Filing Deadlines You Cannot Afford to Miss",
    slug: "vat-filing-deadlines-2026",
    excerpt: "A complete calendar of quarterly and annual VAT deadlines with tips to avoid late-filing penalties.",
    category: { name: "Tax & Compliance", slug: "tax-compliance" },
    author_name: "David Chen",
    published_at: "2026-02-25T14:00:00Z",
    read_time: 5,
    thumbnail_url: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "9",
    title: "How to Set Up Automated Invoice Reminders",
    slug: "automated-invoice-reminders",
    excerpt: "Stop chasing payments manually. Learn how to configure automatic reminders in your invoicing software.",
    category: { name: "Invoicing & Payments", slug: "invoicing-payments" },
    author_name: "Editorial Team",
    published_at: "2026-02-22T09:30:00Z",
    read_time: 6,
    thumbnail_url: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "10",
    title: "Holiday Entitlement: Calculating Leave for Part-Time Staff",
    slug: "holiday-entitlement-part-time",
    excerpt: "The pro-rata calculation explained clearly, with worked examples and a downloadable spreadsheet template.",
    category: { name: "HR & People", slug: "hr-people" },
    author_name: "James Thorne",
    published_at: "2026-02-18T11:15:00Z",
    read_time: 7,
    thumbnail_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "11",
    title: "Double-Entry Bookkeeping Explained in Plain English",
    slug: "double-entry-bookkeeping-explained",
    excerpt: "Debits, credits, and the accounting equation — explained without the jargon so any business owner can follow.",
    category: { name: "Bookkeeping & Accounting", slug: "bookkeeping-accounting" },
    author_name: "Emma Wilson",
    published_at: "2026-02-15T08:00:00Z",
    read_time: 9,
    thumbnail_url: "https://images.unsplash.com/photo-1554224155-1696413565d3?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "12",
    title: "FreeAgent vs Xero: Which Suits Contractors Better?",
    slug: "freeagent-vs-xero-contractors",
    excerpt: "Two popular platforms, one big decision. We compare pricing, features, and contractor-specific tools.",
    category: { name: "Comparison", slug: "comparison" },
    author_name: "Sarah Jenkins",
    published_at: "2026-02-12T13:00:00Z",
    read_time: 11,
    thumbnail_url: "https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "13",
    title: "Running Payroll for the First Time: A Beginner's Checklist",
    slug: "running-payroll-first-time",
    excerpt: "Everything you need to register as an employer, set up PAYE, and process your first payroll run.",
    category: { name: "Payroll", slug: "payroll" },
    author_name: "David Chen",
    published_at: "2026-02-10T10:30:00Z",
    read_time: 8,
    thumbnail_url: "https://images.unsplash.com/photo-1554224154-22dec7ec8818?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "14",
    title: "How to Choose the Right CRM for Your Small Business",
    slug: "choosing-crm-small-business",
    excerpt: "A practical guide to evaluating CRM software against your actual sales process and team size.",
    category: { name: "Cloud Software", slug: "cloud-software" },
    author_name: "Editorial Team",
    published_at: "2026-02-08T09:00:00Z",
    read_time: 7,
    thumbnail_url: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
];
